### ISSUE TITLE
Cache Icons for offline use

### ISSUE THREAD

**Issue by sean-au** [natemoo-re/astro-icon#82] opened 2023-02-09 22:51 UTC
Thanks for creating such a great astro component.

Is it possible to cache icons so site development can continue if the internet cuts out/becomes unavailable?

**Comment by rehhouari** [comment] 2023-02-13 20:59
This would be very helpful because even when online fetching fails often making me unable to work on the site (when it fails big squares are used as placeholders)
there isnt any other good alternative to this package its perfect beside this problem. currently i turn on vpn to solve this issue but it slows things down.

**Comment by stramel** [comment] 2023-03-15 22:07
Thanks for the suggestion! We're actually moving away from the API and more towards a build-time package. This is covered in the v1 rewrite (#87).

I'm going to mark this as duplicate of #54 and track there.

**Closed by stramel** 2023-03-15 22:07 UTC
