### ISSUE TITLE
Devicons do not load on webpage using astro-icons

### ISSUE THREAD

**Issue by Clinton-Nmereole** [natemoo-re/astro-icon#146] opened 2023-10-09 19:12 UTC
This issue is that icons from the pack devicons do not load using astro icons
```astro
---
import { Icon } from "astro-icon";
interface Props {
  text: string;
  logo: string;
}
const { text, logo } = Astro.props;
---

<div class="mx-16">
  <i class={`${logo} text-[120px] p-1 border-gray-100/10 border-2 bg-clip-text text-transparent bg-gradient-to-t from-orange-600 via-gray/70 to-gray/90 rounded-lg`}></i>
  <Icon name="logos:react" class="text-6xl p-2 border-gray-100/10 border-2 bg-clip-text text-transparent bg-gradient-to-t from-orange-600 via-gray/70 to-gray/90 rounded-lg"/>
  <Icon name="devicon-plain:c"/>
  
  <span class="text-2xl ml-6 font-bold bg-clip-text text-transparent bg-gradient-to-t from-orange-600 via-gray/70 to-gray/90 rounded-lg">{text}</span>
</div>
```
In the code above the icon with name "logos:react" loads properly, but "devicon-plain:c" does not load on the page. I tried this for various other icons in the devicon pack and none of them load using astro-icons.
![2023-10-09_14-11](https://github.com/natemoo-re/astro-icon/assets/81373959/17ffae29-5ee6-444d-8bb8-c4cece33dfc2)

**Comment by stramel** [comment] 2023-10-12 22:11
Duplicate of #29

**Closed by stramel** 2023-10-12 22:11 UTC
