### ISSUE TITLE
Stroke width not working for some Iconify icons

### ISSUE THREAD

**Issue by MisterMunchkin** [natemoo-re/astro-icon#256] opened 2024-12-01 11:53 UTC
### What version of `astro-icon` are you using?

^1.1.4

### Astro Info

```block
> portfolio-astro@0.0.1 astro
> astro info

Astro                    v4.16.13
Node                     v20.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/mdx
                         @astrojs/react
                         astro-icon
```

### Describe the Bug

stroke-width is only set on the <svg/> element, so some icons do not get the stroke-width explicitly set my the user.

### What's the expected result?

stroke-width to work for any icon in iconify.

When doing something like:
```
<Icon name="line-md:github-loop" stroke-width={"0.5"} />
```

It will set the stroke-width on the <svg> element instead of the <g> child element for github-loop. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-c9smrf?file=src%2Fpages%2Findex.astro

**Comment by stramel** [comment] 2024-12-26 23:43
Duplicate of #49 and #211

**Closed by stramel** 2024-12-26 23:43 UTC
