### ISSUE TITLE
Some icons are unavailable

### ISSUE THREAD

**Issue by eric-do** [natemoo-re/astro-icon#80] opened 2023-02-02 14:25 UTC
Example failing icon: `tabler:123`
Example passing icon: `tabler:components`

In your `resolver.ts` file you have the base url defined:
```typescript
const baseUrl = https://api.astroicon.dev/v1/
```

When I go to https://api.astroicon.dev/v1/tabler/components, the link does work.

When I go to https://api.astroicon.dev/v1/tabler/123, the link does not work.

According to the [Icon Sets reference ](https://icon-sets.iconify.design/) provided, the `123` icon should work :)

**Comment by POPOEVER** [comment] 2023-02-05 19:36
Same here, `mdi:cloud-tags` missing

**Comment by stramel** [comment] 2023-02-07 18:20
Duplicate of #29 Will continue tracking there

**Closed by stramel** 2023-02-07 18:20 UTC
