### ISSUE TITLE
Build errors on Vercel

### ISSUE THREAD

**Issue by JayBox325** [natemoo-re/astro-icon#93] opened 2023-05-03 18:46 UTC
Please see this error. It happens for all icons, but the build process works perfectly on my local environment:

```
error   [astro-icon] Unable to load icon "basil:linkedin-solid"!
--
19:44:36.540 | Error: Unknown builtin plugin "cleanupIDs" specified.
19:44:36.541 | Error: [astro-icon] Unable to load icon "basil:linkedin-solid"!
19:44:36.541 | Error: Unknown builtin plugin "cleanupIDs" specified.
19:44:36.541 | at file:///vercel/path0/astro/dist/chunks/pages/all.831608ca.mjs:2323:13
19:44:36.541 | at async AstroComponentInstance.render (file:///vercel/path0/astro/dist/chunks/astro.4d0feab3.mjs:1586:7)
19:44:36.541 | at async renderChild (file:///vercel/path0/astro/dist/chunks/astro.4d0feab3.mjs:1643:5)
19:44:36.542 | at async [Symbol.asyncIterator] (file:///vercel/path0/astro/dist/chunks/astro.4d0feab3.mjs:1310:7)
19:44:36.542 | at async renderAstroTemplateResult (file:///vercel/path0/astro/dist/chunks/astro.4d0feab3.mjs:1318:20)
19:44:36.542 | at async renderChild (file:///vercel/path0/astro/dist/chunks/astro.4d0feab3.mjs:1641:5)
19:44:36.542 | at async [Symbol.asyncIterator] (file:///vercel/path0/astro/dist/chunks/astro.4d0feab3.mjs:1310:7)
19:44:36.542 | at async renderChild (file:///vercel/path0/astro/dist/chunks/astro.4d0feab3.mjs:1641:5)
19:44:36.542 | at async renderChild (file:///vercel/path0/astro/dist/chunks/astro.4d0feab3.mjs:1647:5)
19:44:36.585 | Error: Command "npm run build" exited with 1
```

**Comment by tdmichaelis** [comment] 2023-05-03 19:45
I am getting the same error and it is not Vercel specific since running a build locally produces the same errors. I even created  a new astro project and only included astro-icon and a single icon and I am getting the same error.

**Comment by tdmichaelis** [comment] 2023-05-03 20:28
I have this same problem while I am inside a vercel turborepo... I can create a standalone project and it works just fine but when I add that project to a vercel turborepo I get those errors. So maybe it is not specifically an astro-icon problem. I am still digging into the issue.

**Comment by JayBox325** [comment] 2023-05-04 11:51
I have tried this today with a local SVG and it's the same `Unknown builtin plugin "cleanupIDs" specified.` error.

**Comment by jud3v2** [comment] 2023-05-06 15:49
same error on cloudflare

**Comment by stramel** [comment] 2023-05-13 18:28
This looks like it is due to `svgo` version conflict. This should be addressed as part of the v1 rework.

**Comment by YannisHaismann** [comment] 2023-05-16 13:27
Svgo 3.0.+ need to be downgrade to 2.8.0 and set in devDependencies in package.json : 
1. npm install --save-dev svgo@2.8.0
2. Delete package-lock.json & node_modules
3. npm i
4. npm run build

**Comment by stramel** [comment] 2023-05-25 22:17
This a duplicate of #76

**Closed by stramel** 2023-05-25 22:17 UTC
Labels: bug
