### ISSUE TITLE
bug: `astro-icon` is emitting the logic for fetching Astro icons out when using Astro SSG (astro build mode)

### ISSUE THREAD

**Issue by okikio** [natemoo-re/astro-icon#39] opened 2022-06-21 17:37 UTC
`astro-icon` is emitting the logic for fetching Astro icons out when using Astro SSG (astro build mode), even though the expectation is that you get the final svgs

**Comment by stramel** [comment] 2022-10-20 17:22
@okikio I have tested this and I'm unable to reproduce this. Can you provide an example or a reproducible use-case via [astro.new](https://astro.new/)?

**Comment by stramel** [comment] 2022-11-11 16:24
I'm going to close this for now. I'm willing to re-open if we can reproduce the issue described.

**Closed by stramel** 2022-11-11 16:24 UTC
Labels: question
