### ISSUE TITLE
Font Awesome 6 packs don't work (fa6-solid, fa6-regular, fa6-brands)

### ISSUE THREAD

**Issue by andrei-hudovich** [natemoo-re/astro-icon#81] opened 2023-02-08 16:01 UTC
When I try to use one of the `fa6-*` packs, e.g. like this:
```
---
import { Icon } from 'astro-icon'
---

<Icon pack="fa6-solid" name="twitter" />
```

I see this error message in the astro console:
```
Error: Not Found: pack "fa6-brands"
    at request (/node_modules/astro-icon/lib/resolver.ts:17:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async get (/node_modules/astro-icon/lib/resolver.ts:33:10)
    at async Module.load [as default] (/node_modules/astro-icon/lib/utils.ts:153:22)
    at async eval (/node_modules/astro-icon/lib/Icon.astro:22:17)
    at async AstroComponentInstance.render (/node_modules/astro/dist/runtime/server/render/astro/instance.js:36:7)
    at async Module.renderChild (/node_modules/astro/dist/runtime/server/render/any.js:30:5)
```

Direct usage of the API doesn't work too (listed below), all endpoints return a 404 response with a `Not Found: pack "fa6-solid"` message.
```
https://api.astroicon.dev/v1/fa6-solid
https://api.astroicon.dev/v1/fa6-regular
https://api.astroicon.dev/v1/fa6-brands
```

**All the packs are present on Iconify and Icones.**

**Comment by Ravanger** [comment] 2023-02-10 04:23
Came across the same issue. It seems to work with `fa-*` instead of `fa6-*`

**Comment by Boston343** [comment] 2023-02-19 17:50
I'm getting the same error for a number of packs. Some other examples of pack issues are `fluent`, `material-symbols`, and `heroicons`.

**Comment by nlxdodge** [comment] 2023-02-22 19:41
I am not sure how to add this. But my guess would be that not all packs are added by default?

**Comment by stramel** [comment] 2023-03-15 22:03
This is due to an out of date iconify json package on the API. We're working to resolve this in the v1 branch (#87). 

Closing this as a duplicate of #29

**Closed by stramel** 2023-03-15 22:03 UTC
