### ISSUE TITLE
Error: Unknown builtin plugin "cleanupIDs" specified.

### ISSUE THREAD

**Issue by hansrouge** [natemoo-re/astro-icon#72] opened 2022-12-15 09:06 UTC
Hello,

since now I can't build my astro project anymore.
I get the following error:
```error
 error   [astro-icon] Unable to load icon "carbon:phone-filled"!
  Error: Unknown builtin plugin "cleanupIDs" specified.
```
It doesn't matter which icon I am trying to load.

My package json:
```json
{
  "name": "@example/basics",
  "type": "module",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/image": "^0.12.1",
    "@astrojs/netlify": "^1.2.2",
    "@astrojs/partytown": "^1.0.2",
    "@astrojs/sitemap": "^1.0.0",
    "@astrojs/solid-js": "^1.2.3",
    "astro": "^1.6.15",
    "astro-compress": "^1.1.22",
    "astro-icon": "^0.8.0",
    "sharp": "^0.31.2",
    "solid-js": "^1.6.5"
  },
  "devDependencies": {
    "sass": "^1.55.0"
  }
}
```

My Code:
```js
---
import { Icon } from 'astro-icon'
---
<Icon name="carbon:close" />
```

Not sure what's wrong. My last build was a few weeks ago and it worked fine then.

**Comment by philschonholzer** [comment] 2022-12-16 12:29
Have the same problem when deploying on netlify.

```sh
11:34:31 AM: Error: [astro-icon] Unable to load icon "mdi:heart-outline"!
11:34:31 AM: Error: Unknown builtin plugin "cleanupIDs" specified.
```

I'm using `pnpm`, so maybe that causes problems.
I could fix it by adding `svgo` as a dep and downgrading to 2.8.0.

```json
{
  "name": "philipschoenholzer.com",
  "version": "1.1.2",
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "format": "prettier -w src"
  },
  "devDependencies": {
    "@astrojs/image": "^0.12.1",
    "astro": "1.6.15",
    "astro-icon": "^0.8.0",
    "prettier-plugin-astro": "0.7.0",
    "sass": "^1.56.2",
    "sharp": "^0.31.2",
    "svgo": "2.8.0"
  }
}

```

**Comment by soerenmartius** [comment] 2022-12-24 03:46
same issue here

**Comment by TheOtterlord** [comment] 2022-12-28 10:40
Same here

> src/pages/index.astro
 error   [astro-icon] Unable to load icon "mdi:search"!
  Error: Unknown builtin plugin "cleanupIDs" specified.

**Comment by TheOtterlord** [comment] 2022-12-28 18:35
Only when building. It's fine during development

**Comment by jtomek** [comment] 2023-01-03 10:14
same issue here

**Comment by jtomek** [comment] 2023-01-03 10:18
Add a dev dependency svgo version 2.8.0 until this gets resolved.

https://github.com/natemoo-re/astro-icon/issues/65#issuecomment-1309552916

**Comment by stramel** [comment] 2023-01-17 16:43
This is a dependency issue with the v3 major release of SVGO. Going to mark this as a duplicate of #65 for now. There are plans to release this in the next major release.

**Closed by stramel** 2023-01-17 16:43 UTC

**Comment by SiriusBits** [comment] 2023-07-05 12:26
Google brought me here. Same issue. Happy to help solve this in the next one but needed to downgrade SVGO to fix the build.

**Comment by TheJaredWilcurt** [comment] 2024-09-11 18:57
The fix for me was renaming `cleanupIDs` to `cleanupIds`. Lowercase the `D`. Problem solved. (svgo 3.3.2)
