### ISSUE TITLE
unable to use any hero icons

### ISSUE THREAD

**Issue by StevenStavrakis** [natemoo-re/astro-icon#144] opened 2023-09-20 16:09 UTC
As of right now I don't seem to be able to use any hero icons. I should be following the instructions precisely, but still no luck.

**Comment by fayazara** [comment] 2023-09-22 05:41
Same here - behaves randomly works for some icon packs and some dont. 
<img width="1144" alt="Screenshot 22-09 at 11" src="https://github.com/natemoo-re/astro-icon/assets/15716057/c8cb0927-5620-452c-bb2e-983e8a7945b4">

Error - `Error: Not Found: pack "heroicons"`

Here's a reproduction - https://stackblitz.com/edit/github-pzuwww?file=src%2Fpages%2Findex.astro

CC: @natemoo-re

**Comment by StevenStavrakis** [comment] 2023-09-22 14:21
I used the @next branch and followed those instructions and it more or less works. Wait for next release I guess?

**Comment by mmisztal1980** [comment] 2023-10-01 15:26
@StevenStavrakis I'm trying to follow those steps but to no avail, can you let me know what you did to get this to work?

**Comment by StevenStavrakis** [comment] 2023-10-01 17:00
@mmisztal1980 I don't remember exactly but you have to run `npm i astro-icon@next` then follow the instructions for manual install on the [v1 branch](https://github.com/natemoo-re/astro-icon/tree/v1). Install your preferred icon back as per the instructions and it should work.

You have to do the manual install because `astro add` won't work until the new version is published as per [this issue](https://github.com/natemoo-re/astro-icon/issues/87)

**Comment by stramel** [comment] 2023-10-12 22:12
This is a duplicate of #29 if using v0.8.1.

You can also utilize the v1 branch or `next` tag as @StevenStavrakis mentioned.

**Closed by stramel** 2023-10-12 22:12 UTC

**Comment by Avaray** [comment] 2023-12-10 18:51
Just came to check what this hyped Astro is, and it turns out there is no access to all icons from Iconify. Well, we have to wait.
