### ISSUE TITLE
Fix W3C validation

### ISSUE THREAD

**Issue by spokospace** [natemoo-re/astro-icon#90] opened 2023-03-30 10:18 UTC
Currently generated code of each icon looks like this:
`<svg viewBox="0 0 24 24" class="w-5 h-5 hover:text-lightBlue-400" astro-icon="mdi:facebook"><path fill="currentColor" d="M12 2.04c-5.5 0-10 4.49-10 10.02 0 5 3.66 9.15 8.44 9.9v-7H7.9v-2.9h2.54V9.85c0-2.51 1.49-3.89 3.78-3.89 1.09 0 2.23.19 2.23.19v2.47h-1.26c-1.24 0-1.63.77-1.63 1.56v1.88h2.78l-.45 2.9h-2.33v7a10 10 0 0 0 8.44-9.9c0-5.53-4.5-10.02-10-10.02z" /></svg>`

which is error in W3C validators:
`Error: Attribute astro-icon not allowed on element svg at this point`
![image](https://user-images.githubusercontent.com/16397823/228805887-95eeb13b-c3ef-4dc6-9fc1-d9adffb5d586.png)

it seems to me, this part with 'astro-icon' should be removed from svg code

**Comment by stramel** [comment] 2023-04-09 01:40
This is a duplicate of #55

**Closed** 2023-04-09 01:41 UTC
