### ISSUE TITLE
Icon not found

### ISSUE THREAD

**Issue by lyqht** [natemoo-re/astro-icon#48] opened 2022-08-05 09:20 UTC
Got the following error

```
Error: Not Found: "newspaper" in pack "charm"
    at request (/node_modules/astro-icon/lib/resolver.ts:17:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

However, I've checked from the charm icon pack that [it exists](https://icon-sets.iconify.design/charm/newspaper/).

**Comment by manuelmeister** [comment] 2022-10-06 07:24
This probably has to do with #29

**Comment by stramel** [comment] 2022-10-20 17:00
Yep, duplicate of #29

**Closed by stramel** 2022-10-20 17:00 UTC
Labels: duplicate
