### ISSUE TITLE
Updating to `svgo@3` causes issues

### ISSUE THREAD

**Issue by itsmatteomanf** [natemoo-re/astro-icon#65] opened 2022-10-27 21:05 UTC
I updated `astro-compress` to its latest `1.1.1` release and this broke icons as it brought with it `svgo@3`. Not fully sure it's an issue with `astro-icon`, might very likely be upstream at Astro itself, but I cannot guarantee it...

This made a change on the `cleanupIDs` plugin, which is now called `cleanupIds`.

I have now pinned `astro-compress` to 1.0.12 especially as the `1.1` feature wasn't of interest in my case, but it might be worth updating this package to support `svgo@3`.

Reference for `svgo@3`: https://github.com/svg/svgo/releases/tag/v3.0.0.

```
file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:1746
      throw new Error(`[astro-icon] Unable to load icon "${name}"!
            ^

Error: [astro-icon] Unable to load icon "wifi-slash-regular"!
Error: Unknown builtin plugin "cleanupIDs" specified.
    at file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:1746:13
    at async renderToIterable (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:745:21)
    at async renderAstroComponentInline (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:973:24)
    at async renderChild (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:671:5)
    at async AstroComponent.[Symbol.asyncIterator] (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:703:7)
    at async renderAstroComponent (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:714:20)
    at async renderAstroComponentInline (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:974:9)
    at async renderChild (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:671:5)
    at async AstroComponent.[Symbol.asyncIterator] (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:703:7)
    at async renderAstroComponent (file:///Users/matteo/GitHub/[repo]/dist/entry.mjs?time=1666904273871:714:20)
```

**Comment by SamiFala** [comment] 2022-10-27 23:45
Exactly same issue at the same time bro

**Comment by stramel** [comment] 2022-10-28 14:42
That's unfortunate that v3 was released in a minor bump to the project. It's always tough to handle common tooling major bumps without any issues downstream.

For now, you will have to fix your `astro-compress` versions to a specific version `1.0.12` until we have time to update our code.

We do have a plan to move to `svgo@3` in the near future.

**Comment by itsmatteomanf** [comment] 2022-10-28 14:45
> That's unfortunate that v3 was released in a minor bump to the project. It's always tough to handle common tooling major bumps without any issues downstream.

Yeah, which is what caused me to investigate. It wasn't immediately obvious as it being a minor bump only I didn't expect to have issues, especially as `astro-compress` runs after everything is done.

Happy to see a solution will be found, hopefully soon. Thanks!

**Comment by smithbm2316** [comment] 2022-11-09 23:49
I personally found a resolution to this by adding `svgo` as a dev dependency and pinning it to version `2.8.0` (`pnpm add -D svgo@2.8.0`). seems to work as intended for me in both my astro dev server and builds!

**Comment by feraleyebrows** [comment] 2023-02-19 22:58
I have found an elegant fix for this for pnpm users.

First create a .pnpm-workspace.yaml file in your project root.

Paste this into it:

```yaml
# pnpm-workspace.yaml
packages:
  - "packages/*"
```

Next create a directory called 'packages' at project root. Inside that directory create another directory called `svgo`. Inside the `svgo` directory create two files, a `package.json` and an `index.js` file. Open the files and copy and paste the following into them:

// packages/svgo/package.json
```json
{
    "name": "svgo",
    "type": "module",
    "version": "0.0.1",
    "private": true,
    "scripts": {},
    "dependencies": {
        "svgo": "^2.8.0"
    }
}
```

// packages/svgo/index.js
```js
import svgo from "svgo";

export default svgo
```

Now cd into the svgo directory if you haven't already and run `pnpm install`. You should now have a `node_modules` directory inside the svgo directory.

Finally return to your project root and create a file called `.pnpmfile.cjs`. Populate it with the following:

// .pnpmfile.cjs
```js
function readPackage(pkg, context) {
    if (pkg.name === 'svgo' && pkg.version.startsWith('^2.')) {
        pkg.dependencies.svgo = "workspace:*"

    }
    return pkg
}

module.exports = {
    hooks: {
        readPackage
    }
}
```

On running `pnpm run build` everything should now build properly, assigning v2 of svgo to astro-icon and v3 to astro-compress.

**Closed** 2023-12-22 19:59 UTC
Labels: enhancement
