### ISSUE TITLE
Bootstrap icons

### ISSUE THREAD

**Issue by csjui** [natemoo-re/astro-icon#118] opened 2023-06-19 05:13 UTC
Hi, how does one use bootstrap icons in this? I've tried using bi:airplane etc., with no luck. 

e.g. `<Icon pack="bi" name="airplane" size="24" color="blue" />`

I saw a closed issue regarding bootstrap icons that said support was implemented, but I've been unable to find out how. 

Thanks

**Comment by stramel** [comment] 2023-06-19 12:37
Hi @csjui thank you for filing this issue! Looking into this, the pack does exist but it appears that the icon doesn't exist in the version being utilized by our v0. This will be resolved by the v1. There are a couple workarounds if you want to try to use the icon now.

For now I'm going to close this as a duplicate of #29 since it is still a missing icon issue.

**Closed by stramel** 2023-06-19 12:37 UTC
Labels: bug, duplicate
