### ISSUE TITLE
Bump svgo to 3.0.2

### ISSUE THREAD

**Issue by redwerkz** [natemoo-re/astro-icon#75] opened 2022-12-31 02:36 UTC
The latest svgo introduced a breaking change..
[Rename cleanupIDs to cleanupIds for consistency #1049](https://github.com/svg/svgo/pull/1049)

..that causes builds to break
[Error: Unknown builtin plugin "cleanupIDs" specified. #72](https://github.com/natemoo-re/astro-icon/issues/72)
[Updating to svgo@3 causes issues #65](https://github.com/natemoo-re/astro-icon/issues/65)

**Comment by stramel** [comment] 2023-01-17 16:41
This is something that I plan on adding to the next major version. I have been offline for the holidays and just getting back to catching up to it. Going to mark this as a duplicate of #65

**Closed by stramel** 2023-01-17 16:41 UTC
