### ISSUE TITLE
Will icons be used in framework components?

### ISSUE THREAD

**Issue by recallwei** [natemoo-re/astro-icon#92] opened 2023-04-22 15:31 UTC
I want to use icons in framework components (React or Vue).
Currently seems not to support.

**Comment by recallwei** [comment] 2023-04-24 00:10
Currently, Astro components can be passed through slots. Is it possible to use them directly in framework components?

**Comment by stramel** [comment] 2023-05-13 18:24
It is not possible to use `astro-icon` directly in other framework components. You can use them inside framework components using slots. 

Will work to add documentation around this.

Closing this as a duplicate of #41

**Closed by stramel** 2023-05-13 18:24 UTC
Labels: duplicate
