### ISSUE TITLE
The future of `astro-icon`

### ISSUE THREAD

**Issue by natemoo-re** [natemoo-re/astro-icon#87] opened 2023-03-06 14:51 UTC
Hey y'all! Sorry I haven't been on top of the maintenance here.

`astro` looked very different back when the first version of `astro-icon` was built. There was no integration system and SSR was just an idea we had. As such, the current version of `astro-icon` makes some assumptions about your project that are no longer true.

I've started working on a new version of `astro-icon` that will:
- be a proper integration
- support SSR
- not use `svgo` at runtime
- not rely on a custom API service
- have a peer dependency on `@iconify/json` so you can always keep it in sync
- have much better error messages
- 

If you're interested, here's a StackBlitz with my initial exploration. I plan to move this into a branch and work towards a `v1` of `astro-icon` in the coming weeks.

If you'd like to get involved, please reach out on the Astro Discord!

https://github.com/natemoo-re/astro-icon/tree/v1

**Comment by okikio** [comment] 2023-03-07 03:26
@natemoo-re Looks awesome 👍🏽

**Comment by natemoo-re** [comment] 2023-03-07 16:21
> @natemoo-re right now astro icons can't be used in the SSR environment?

It can, but it introduces some potential network latency and a dependency on the `astro-icon` API, which could theoretically go down. I'm working on a more optimized approach that removes that network dependency.

**Comment by arnorhs** [comment] 2023-04-10 21:06
Awesome, i was just bumping into an issue deploying with ssr on cloudflare, so that's great news.

what is the state of it, is there an RFC? something you'd appreciate help with?

**Comment by GrantBirki** [comment] 2023-04-15 07:46
I am very excited for this

**Comment by GrantBirki** [comment] 2023-05-02 21:53
👋 Hey @natemoo-re! Super excited for this feature and wondering if there has been any additional progress made on this? Thanks in advance!

**Comment by AyushSehrawat** [comment] 2023-05-10 13:52
Great! Faced deployment issues on cloudflare :/. Commenting here so that i can follow up with the progress :)

**Comment by ddlaws0n** [comment] 2023-05-12 07:02
Fantastic news! Astro Icon has been very enjoyable to use (other than the `svgo` issues). Hope to see great things soon :)

**Comment by surjithctly** [comment] 2023-05-14 03:26
Awesome. Are there any plans to move this to  official Astro Plugins?

**Comment by sonicjhon1** [comment] 2023-05-19 15:29
Any news on this?

**Comment by stramel** [comment] 2023-05-21 14:28
I'm working on getting the code to a good state and ensuring we're hitting all the use-cases.

**Comment by stramel** [comment] 2023-05-25 20:00
Can anyone try out this version the v1 for me? 

You can install it using: `npm install https://github.com/natemoo-re/astro-icon.git#ms/v1`

You can read instructions here: https://github.com/natemoo-re/astro-icon/blob/ms/v1/packages/core/README.md

**Comment by stramel** [comment] 2023-05-25 20:16
Would anyone be willing to test this version of the `v1` branch out for me?

You can install it using: `npm i "https://gitpkg.now.sh/natemoo-re/astro-icon/packages/core?ms/v1"`

You can read how to use it here: https://github.com/natemoo-re/astro-icon/blob/ms/v1/packages/core/README.md

Migration notes: Ensure your `Icon` imports from `astro-icon/components` now!

Thanks in advance for any and all feedback!

**Comment by ddlaws0n** [comment] 2023-05-26 07:08
Hey @stramel ! Thrilled to see movement on `v1` :)

Had a chance to test this out this morning: https://github.com/ddlaws0n/astro-icon-v1-testing
Not working for me unfortunately, unless I'm doing something wrong:

<img width="800" alt="image" src="https://github.com/natemoo-re/astro-icon/assets/24451678/c571de0c-20f7-4b48-b98e-2cdf8645f7e4">

**Comment by stramel** [comment] 2023-05-26 12:49
Thanks @ddlaws0n! Looks like my local version had cached. This was a missing extension which resulted in bad imports. 

I have pushed a fix. You may need to remove the existing dependency and then re-install it using the steps I posted previously.

**Comment by mattpaz** [comment] 2023-05-26 14:20
Just tried it.  Looks promising, but but here are my results:

When I start up astro, I get ... 
`[astro-icon] "mdi" does not appear to be a valid iconify collection!`

My integrations:
```
  integrations: [
    icon({
      iconDir: 'src/assets/icons',
      include: {
        mdi: ['check'], // Only loads the Material Design Icon's "account" SVG
      }
    }),
    tailwind({
      config: {
        applyBaseStyles: false
      }
    }),
    svelte()
  ]
```  

And from the page I was loading an icon from ... 

`import { Icon } from 'astro-icon/components';`
`<h2><Icon name="mdi:check" /> Testing </h2>`

<img width="1244" alt="image" src="https://github.com/natemoo-re/astro-icon/assets/854153/7f32d6ed-f7cf-42ad-869a-5a86b26fa01a">

```
Error: Unable to locate "mdi:check" icon!
    at eval (/node_modules/astro-icon/components/Icon.astro:26:17)
    at AstroComponentInstance.Icon [as factory] (/node_modules/astro/dist/runtime/server/astro-component.js:22:12)
    at AstroComponentInstance.init (/node_modules/astro/dist/runtime/server/render/astro/instance.js:26:29)
    at AstroComponentInstance.render (/node_modules/astro/dist/runtime/server/render/astro/instance.js:31:18)
    at render.next (<anonymous>)
    at Module.renderChild (/node_modules/astro/dist/runtime/server/render/any.js:30:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EagerAsyncIterableIterator.next (/node_modules/astro/dist/runtime/server/render/util.js:148:14)
    at async RenderTemplateResult.[Symbol.asyncIterator] (/node_modules/astro/dist/runtime/server/render/astro/render-template.js:43:7)
    at async Module.renderAstroTemplateResult (/node_modules/astro/dist/runtime/server/render/astro/render-template.js:51:20)
    ```
    
 Perhaps I miss configured something?

**Comment by stramel** [comment] 2023-05-26 17:44
@mattpaz Did you install `@iconify-json/mdi` or `@iconify/json`?

**Comment by mattpaz** [comment] 2023-05-27 02:03
@stramel Ah, you're right.  I didn't actually anticipate needing to to that, but after adding `@iconify-json/mdi` it seemed to work well.  Thanks!

**Comment by stramel** [comment] 2023-05-27 02:07
Awesome! I'm looking into adding an auto install flag which would handle that for you but we'll see if that happens

**Comment by djmtype** [comment] 2023-06-27 23:20
I can't seem to get my Astro project to build with astro-icon v1 alpha. Everything works just fine in dev. However, when I build, it claims that I haven't installed some random icon package from @iconify/json. I am only using the remix iconset which I have installed `"@iconify-json/ri": "^1.1.10",` and explicitly set up in my Astro config under `integrations`: 

```js
icon({
      include: {
          ri: ['*']
      }
  }),
```

It looks like the issue occurs when I'm using astro icon as a nested component such as `<Icon name={featuredIcon} size={128} />`. 
Anyone else running into this problem?

**Comment by djmtype** [comment] 2023-06-27 23:39
Has anyone tried deploying their Astro project to Netlify with astro-icon v1 alpha, and had success? Mine fails during build with a very vague error. Since this is the only thing that has changed in my Astro project, I'm only making an educated guess it's astro-icon v1 alpha.

**Comment by stramel** [comment] 2023-06-28 00:06
> Has anyone tried deploying their Astro project to Netlify with astro-icon v1 alpha, and had success? Mine fails during build with a very vague error. `Failed during stage 'building site': Build script returned non-zero exit code: 2`
> 
> My package.json includes: `"astro-icon": "https://gitpkg.now.sh/natemoo-re/astro-icon/packages/core?v1-alpha"`
> 
> Since this is the only thing that has changed in my Astro project, I'm only making an educated guess the cause might be  astro-icon v1 alpha. 
> 
> BTW, locally, everything builds fine. No errors, and the preview works.

Can you provide any other error outputs? In the meantime, I'll see if I can find any issues

**Comment by djmtype** [comment] 2023-06-28 13:05
@stramel BTW, If I remove the src/icons directory from my project, it fails on local and on Netlify which is why I added the directory to my project even though I'm not using it. 

In order to avoid the error on Netlify, I had to add some arbitrary svg file to fix the build error.

**Comment by stramel** [comment] 2023-06-28 13:05
> @stramel BTW, I have a `src/icons` directory in my project, but it's empty because I'm not using it; only icons from `@iconify-json`. So, while this works on local, it doesn't on Netlify. 
> 
> Here's the error I'm getting only on Netlify: 
> ```
> [astro-icon] Could not load virtual:astro-icon (imported by node_modules/astro-icon/components/Icon.astro): ENOENT: no such file or directory, scandir 'src/icons/'
> 7:42:24 PM:  error   Could not load virtual:astro-icon (imported by node_modules/astro-icon/components/Icon.astro): ENOENT: no such file or directory, scandir 'src/icons/'
> 7:42:24 PM: Error: Could not load virtual:astro-icon (imported by node_modules/astro-icon/components/Icon.astro): ENOENT: no such file or directory, scandir 'src/icons/'
> ```
> 
> Here's my astro-icon config. I also tried manually adding `iconDir` afterwards. It didn't matter. Error persists on Netlify. 
> 
> ```
> icon({
>       iconDir: 'src/icons',
>       include: {
>           ri: ['*'],
>           ion: ['*'],
>           bx: ['*'],
>           ic: ['*'],
>           'simple-icons': ['*']
>       }
>   }),
> ```

Thanks, I'll take a look! I noticed this locally when running the build too.

**Comment by stramel** [comment] 2023-06-29 21:50
We have just published a prerelease version of the v1 to npm. You can install it using `npm i astro-icon@next` or `npm i astro-icon@1.0.0-next.1` if you want the specific version! Please feel free to file an issue or let us know if you run into any issues!

**Comment by GrantBirki** [comment] 2023-06-30 02:27
👋 Hey @stramel! I saw your comment above and tried to give the `next` tag a go. Unfortunately I'm running into errors when running `npm run build`. The changes (via a PR) and the error can be found here: https://github.com/GrantBirki/astrowind/pull/127#issuecomment-1614026370

**Comment by stramel** [comment] 2023-06-30 03:55
Thank you, we really appreciate the detailed feedback! I'll take a look at trying without a pack to see if we can clean up the error messaging on that. Strange that the error message looked like it was referring to the v0 astro-icon code.

**Comment by GrantBirki** [comment] 2023-06-30 04:03
It should also be noted that I don't actually use any local icon packs at the moment. I only use the npm packages that get installed from `@iconify-json/<value>` So I find the error message `Unable to load local collection. Ensure you have your iconDir configured properly.` to be odd.

Also, @stramel I merged all the changes into `main` and you can check them out here: https://github.com/GrantBirki/astrowind

The project works as expected apart from that one weird `iconDir` message so I consider your `v1` branch to be a huge success!

**Comment by stramel** [comment] 2023-06-30 04:07
@GrantBirki Fantastic! Glad to hear that it's working as expected!

We'll discuss the message about the iconDir. I think there might be a better place to alert about the local collection.

**Comment by stramel** [comment] 2023-06-30 04:54
@GrantBirki I just published a new version that only alerts about local directory when using and not having it configured properly. Pushed to the `next`  tag and `1.0.0-next.2`. Hopefully this gets rid of the unnecessary warnings when not using local icon sets.

**Comment by GrantBirki** [comment] 2023-07-02 16:44
Works perfectly, thanks!

https://github.com/GrantBirki/astrowind/pull/131

**Comment by tusamni** [comment] 2023-07-05 14:45
I'm having issues with local icons and subdirectories in the `icons` folder. I had to put all the icons in the root `icons` directory and it seems to be working now.

**Comment by stramel** [comment] 2023-07-05 16:03
> I'm having issues with local icons and subdirectories in the `icons` folder. I had to put all the icons in the root `icons` directory and it seems to be working now.

Thanks for the details! I will look into this. It should work in subdirectories

**Comment by stramel** [comment] 2023-07-05 16:23
@tusamni I just tested locally with a custom `iconDir` and the default without being able to reproduce. Can you provide more details to help reproduce the issue?

**Comment by tusamni** [comment] 2023-07-05 16:40
I'm referencing the icons like this:

`<Icon name="jobs/icg" class:list={["absolute", c.size]} />`

I'm bringing in the component here: `import { Icon } from "astro-icon/components";`

My icon folder below:
![image](https://github.com/natemoo-re/astro-icon/assets/9271145/23cc76ff-8093-4aa5-856d-ee7304977f07)

I'm getting this error:
```An error occurred.
Unable to locate "jobs/icg" icon!
The icon named "jobs/icg" was not found in your local icon directory.```

**Comment by tusamni** [comment] 2023-07-05 16:48
Ah interesting. That did work.

Thanks for clarifying that!

**Comment by surjithctly** [comment] 2023-07-18 07:18
I just tried the new version. after adding a custom iconfity package, I started to get this strange error. but then the error did not go even after removing that. Finally, I had to replace old `astro-icon` to fix the issue. 

```
ReferenceError: An error occurred.
require is not defined
find-up/index.js:2:14
'use strict';
const path = require('path');
```

**Comment by surjithctly** [comment] 2023-07-18 07:31
Also `pnpm astro add astro-icon@next` doesn't seem to be working as per the Readme. 

![CleanShot 2023-07-18 at 12 57 06](https://github.com/natemoo-re/astro-icon/assets/1884712/0d9212f2-9cef-4f17-a267-b3c7291fbfad)

**Comment by cachitas** [comment] 2023-07-21 23:50
> Also `pnpm astro add astro-icon@next` doesn't seem to be working as per the Readme.
> 
> ![CleanShot 2023-07-18 at 12 57 06](https://user-images.githubusercontent.com/1884712/254177771-0d9212f2-9cef-4f17-a267-b3c7291fbfad.png)

I think you should use pnpm/npm/yarn directly and not `astro add`.

Quoting the README from both `main` and `next` branches:
```
npm i astro-icon
# or
yarn add astro-icon 
```

**Comment by surjithctly** [comment] 2023-07-22 03:44
@cachitas Wait, shouldn’t the new branch is called v1? 

https://github.com/natemoo-re/astro-icon/tree/v1

**Comment by stramel** [comment] 2023-07-22 05:53
> @cachitas Wait, Isn’t the new branch called v1? 
> 
> https://github.com/natemoo-re/astro-icon/tree/v1

I don't believe the `astro add` will work until we publish it under the stable instead of next. 

For now use the manual instructions but install using `npm i astro-icon@next` to get the V1 changes.

**Comment by stramel** [comment] 2023-10-12 22:18
Sorry for the lack of communication here. We're currently stalled on the SSR DX and waiting for direction on the core SVG integration into Astro. (https://github.com/withastro/roadmap/issues/699)

**Comment by jefferykarbowski** [comment] 2023-11-07 21:01
I am getting "Error: Unable to load the "local" icon set!" when trying to use an local icons in /src/icons directory. I am on next.2. Please advise.

`
Error: Unable to load the "local" icon set!
hint: 'It looks like the "local" set was not loaded.\n' +
    '\n' +
    'Did you forget to create the icon directory or to update your config?'
`

**Comment by fflaten** [comment] 2023-11-10 20:37
I'm confused. How are you all testing `next` when the `astro-icon/components` export points to `./components/index.js` which is missing? From what I can see the components folder is never compiled but the typescript source is packaged. I must be doing something very stupid and wrong - please help 😄

**Closed** 2023-12-22 19:59 UTC
