### ISSUE TITLE
No `simple-icons:pocketbase`

### ISSUE THREAD

**Issue by ThatOneCalculator** [natemoo-re/astro-icon#66] opened 2022-10-31 01:22 UTC
Despite it being listed as an icon:

![image](https://user-images.githubusercontent.com/44733677/198912953-b58fdb19-5f17-463c-836b-da5f3f3bb662.png)

I get this error:

```
Error: Not Found: "pocketbase" in pack "simple-icons"
    at request (/node_modules/astro-icon/lib/resolver.ts:17:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

![image](https://user-images.githubusercontent.com/44733677/198912982-9f2301e5-7f2b-4e4b-b604-efd5b57c337d.png)

**Comment by stramel** [comment] 2022-10-31 15:36
Duplicate of #29

**Closed by stramel** 2022-10-31 15:36 UTC
